name: onebike_shopping_app_flutter
description: "Online Bike shopping app in flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.3.1
  carousel_slider:
  gap: ^3.0.1
  swipeable_button_view: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/